version: '3.7'
services:

  mongo:
    image: mongo
    command: --replSet rs0

  redis:
    image: redis

  smartproxy:
    build:
      context: .
      dockerfile: SmartProxy.Dockerfile
    ports:
      - "9000:80"
    depends_on:
      - redis

  microservice:
    build:
      context: .
      dockerfile: Microservice.Dockerfile
    depends_on:
      - smartproxy